"""Deterministic, local-only display projection of isolated monitor research.

No model aliases, official approval, compatibility or new source facts are inferred.
"""
import argparse
import copy
import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from scripts.validate_monitor_expansion import load, official

SOURCE = ROOT / 'data/research/monitor-expansion/official_specs.json'
JSON_OUTPUT = ROOT / 'data/site/monitor-v3.json'
JS_OUTPUT = ROOT / 'web/monitor-v3-data.js'
NUMERIC_FIELDS = {
    'size': ('inch', 'PANEL'),
    'width': ('px', 'NATIVE_RESOLUTION'),
    'height': ('px', 'NATIVE_RESOLUTION'),
    'refresh': ('Hz', 'PANEL'),
}
VIDEO_MODES = {'DP Alt Mode', 'DP Alt Mode + data', 'DP Alt Mode + Data',
               'DP Alternate', 'DP alt'}


def select_filter(facts, key):
    """Return a value and its fact IDs only when all eligible facts agree."""
    selected = []
    for fact in facts:
        if fact['qualifier'] == 'UNKNOWN':
            continue
        value = fact['value']
        if key in NUMERIC_FIELDS:
            unit, scope = NUMERIC_FIELDS[key]
            if (fact['property'] == key and fact['unit'] == unit and
                    fact['scope'] == scope and type(value) in (int, float) and
                    math.isfinite(value) and value > 0 and
                    (key not in {'width', 'height'} or float(value).is_integer())):
                selected.append((value, fact['id']))
        elif key == 'panel':
            if (fact['property'] == 'panel' and fact['scope'] == 'PANEL' and
                    fact['unit'] is None and isinstance(value, str) and value.strip()):
                selected.append((value, fact['id']))
        elif key == 'usb_c_video':
            if fact['property'] != 'usb_c' or fact['scope'] != 'PORT' or fact['unit'] is not None:
                continue
            if value is False:
                selected.append((False, fact['id']))
            elif isinstance(value, dict) and isinstance(value.get('mode'), str) and value['mode'] in VIDEO_MODES:
                selected.append((True, fact['id']))
    if not selected or any(item[0] != selected[0][0] for item in selected):
        return None, []
    return selected[0][0], [item[1] for item in selected]


def build(source):
    official(source)  # Validate original envelope, references and evidence before projection.
    result = copy.deepcopy(source)
    result['source_path'] = SOURCE.relative_to(ROOT).as_posix()
    for product in result['products']:
        product['filters'] = {}
        product['filter_fact_refs'] = {}
        product['review_status'] = 'PENDING_HUMAN_REVIEW'
        product['usable_for_compatibility'] = 'NO'
        for key in (*NUMERIC_FIELDS, 'panel', 'usb_c_video'):
            value, refs = select_filter(product['facts'], key)
            product['filters'][key] = value
            product['filter_fact_refs'][key] = refs
    return result


def serialized(source):
    raw = json.dumps(build(source), ensure_ascii=False, indent=2, allow_nan=False) + '\n'
    # Escaping also keeps future source text safe if embedded in an HTML script.
    js = raw.replace('<', '\\u003c').replace('\u2028', '\\u2028').replace('\u2029', '\\u2029')
    return raw, '// Generated by scripts/build_monitor_v3.py; do not edit.\nwindow.CONNECTABLE_MONITORS = ' + js.rstrip() + ';\n'


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail on missing/stale derived artifacts')
    args = parser.parse_args(argv)
    artifacts = zip((JSON_OUTPUT, JS_OUTPUT), serialized(load(SOURCE)))
    stale = []
    for path, content in artifacts:
        if args.check:
            if not path.exists() or path.read_bytes() != content.encode('utf-8'):
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8')
    if stale:
        print('FAIL: stale/missing derived files: ' + ', '.join(stale), file=sys.stderr)
        return 1
    print('PASS: monitor v3 derived display data; public UNKNOWN')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
