"""Generate the read-only mockup projection from authoritative JSONL."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
TITLES = {
'UQ-0007':'화면 두 개, 복제와 확장의 차이', 'UQ-0009':'해결된 연결 문제가 다시 나타났어요',
'UQ-0010':'여러 디스플레이, 갈라지는 연결 경로', 'UQ-0012':'여러 번의 연결 시도 끝에 찾은 구성',
'UQ-0022':'허브 하나에서 두 화면으로 연결하기', 'UQ-0014':'업데이트 이후 외장 화면이 불안정해요',
'UQ-0024':'같은 USB-C, 다른 입력 포트의 결과', 'UQ-0025':'모니터를 하나 더 연결하기 전에',
'UQ-0006':'직접 HDMI는 정상, 허브에서는 색상 문제', 'UQ-0008':'50Hz 영상 출력과 남은 오디오 문제',
'UQ-0013':'듀얼 HDMI 장치 교체 후 세 화면 사용', 'UQ-0015':'맥북은 인식하는데 모니터는 검은 화면',
'UQ-0017':'사용자 계정마다 다른 디스플레이 인식', 'UQ-0019':'1080 이상 해상도를 선택할 수 없어요',
'UQ-0020':'데스크톱과 휴대용 모니터 연결 고민', 'UQ-0023':'4K 화면 출력과 영상 재생은 다른 문제',
}
def build():
    records = [json.loads(line) for line in (ROOT/'data/research/user_questions_v2.jsonl').read_text().splitlines()]
    # Show Apple cases first; broader research cases remain explicitly user reports.
    records.sort(key=lambda r: (not any(n.get('family','').startswith('MacBook') for n in r['nodes']), r['id']))
    result=[]
    for r in records:
        source=next(n for n in r['nodes'] if n['kind']=='SOURCE')
        result.append(dict(id=r['id'],title=TITLES[r['id']],sourceModel=source.get('display_model','모델 미상'),
            goal=r['goal']['summary'],summary=r['outcome']['summary'],outcome=r['outcome']['status'],
            observations=[o['summary'] for o in r['observations']],notes=r['review']['notes'],
            url=r['source']['source_url'],site=r['source']['site_name'],checked=r['source']['checked_at']))
    payload=json.dumps(result,ensure_ascii=False,separators=(',',':')).replace('<','\\u003c')
    return '// Generated by scripts/build_mockup_cases.py; do not edit.\nwindow.CONNECTABLE_CASES = '+payload+';\n'
if __name__=='__main__':
    (ROOT/'web/cases.js').write_text(build(),encoding='utf-8')
    print('Generated web/cases.js from authoritative JSONL')
