"""Generate a read-only local UI projection; never write to research originals."""
import copy
import json
from pathlib import Path
from urllib.parse import urlsplit
from scripts import validate_public_usage_review as review

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'web/review-data.js'
TITLES = [
    'V32UE의 영상·충전과 UI 배율', 'C-C와 SOHO Dock HDMI의 다른 결과',
    'M7의 직접 연결과 여러 비교 경로', '30Hz 선택 제한과 아직 수행하지 않은 교체',
    'Mac과 Windows에서 이어지는 깜빡임', '칩 미상 MacBook의 클램쉘 사용 보고',
    'MSI 직접 연결과 Belkin 독 경유 비교', '허브 교체·잠자기 복귀·덮개 전환',
    '미러링 전환으로 임시 정상, 재연결 뒤 재발', 'U28E590D의 초기 출력 문제와 제품 소개',
    '4K 선택 가능 여부와 60/30Hz 설정', 'MH510의 DP 영상과 동시 충전 보고',
    'PD2307의 세 화면 연결과 일부 복제', 'MSI 케이블 교체와 관측 당시 호스트 미상',
    'DisplayLink 설치 후 두 화면 사용', '기존 허브 4K30과 UGREEN 4K60 진술',
    'FHD120 출력과 144Hz 선택 후 검은 화면', '일체형 허브의 케이스 장착 간섭',
]


def safe_external_url(value):
    parsed = urlsplit(value)
    host = parsed.hostname or ''
    return (parsed.scheme == 'https' and not parsed.username and not parsed.password
            and '.' in host and any(c.isalpha() for c in host)
            and host != 'localhost' and not host.endswith(('.local', '.internal')))


def build(mapping_path=review.MAPPING, source_path=review.SOURCE):
    errors = review.validate_files(mapping_path, source_path)
    if errors:
        raise ValueError('Review mapping validation failed; no asset generated')
    records = []
    for _, r, _ in review.read_jsonl(mapping_path):
        m = r['mapping']
        if not safe_external_url(m['source']['source_url']):
            raise ValueError('Only public HTTPS source links may enter the UI')
        item = dict(id=r['source_id'], title=TITLES[int(r['id'].split('-')[1])-1],
                    source=copy.deepcopy(m['source']), grade='C', reviewStatus='NEEDS_REVIEW',
                    publicStatus='UNKNOWN', basis='USER_REPORT',
                    environment=copy.deepcopy(m['environment']),
                    nodes=copy.deepcopy(m['nodes']), ports=copy.deepcopy(m['ports']),
                    configurations=copy.deepcopy(m['configurations']), goal=copy.deepcopy(m['goal']),
                    attempts=copy.deepcopy(m['attempts']), observations=copy.deepcopy(m['observations']),
                    functionalObservations=copy.deepcopy(r['functional_observations']),
                    evidence=copy.deepcopy(m['evidence']),
                    evidenceRoles=[{k:v for k,v in a.items() if k!='source_pointers'}
                                   for a in copy.deepcopy(r['evidence_annotations'])],
                    unscopedStatements=copy.deepcopy(r['unscoped_statements']),
                    missing=copy.deepcopy(m['review']['missing_fields']),
                    commercial=copy.deepcopy(m['review']['commercial_context']))
        if 'semantic_review' in r:
            item['semanticReview'] = copy.deepcopy(r['semantic_review'])
        records.append(item)
    records.sort(key=lambda r:r['id'])
    data = dict(version='review-ui-1', recordStatus='REVIEW_ONLY', publicStatus='UNKNOWN',
                approvedGold=0, records=records)
    payload = json.dumps(data, ensure_ascii=False, separators=(',',':'))
    payload = payload.replace('<', '\\u003c').replace('\u2028','\\u2028').replace('\u2029','\\u2029')
    return '// Generated by scripts/build_public_usage_review_ui.py; do not edit.\nwindow.CONNECTABLE_REVIEW_DATA = '+payload+';\n'


if __name__=='__main__':
    OUTPUT.write_text(build(),encoding='utf-8')
    print('Generated web/review-data.js: 18 review-only cases, no approval')
